version: '3.8'

services:
  db:
    container_name: pg_cont
    image: docker.io/postgres:17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/pg-data:/var/lib/postgresql/data
    networks:
      - my_network

  metabase:
    container_name: metabase_cont
    image: metabase/metabase:latest
    platform: linux/amd64 # <- **關鍵修改：強制使用 x86-64 架構**
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=db
      - MB_DB_PORT=5432
      - MB_DB_USER=db_user
      - MB_DB_PASS=postgres
      - MB_DB_HOST=db
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
